alias {{alias_su_rubyuser}}='su - rubyuser'
alias {{alias_su_phpuser}}='su - phpuser'
alias {{alias_su_pythonuser}}='su - pythonuser'
alias {{alias_su_jsuser}}='su - jsuser'
alias dnf='/root/bin/dnf.sh'
